---
### Make the required changes to the sudoers file for the wheel group and
### the scomsvc user
#

- name: Change the owner of the tmp dir to root.root and permissions to 1777
  action: shell cd /; chmod 1777 tmp

- name: Bring over the zabbix-release-4.4-1.el7.noarch.rpm into /tmp
  action: copy src=rpms/zabbix_agent-5.0.5-linux-3.0-amd64-static.tar.gz dest=/tmp/zabbix_agent-5.0.5-linux-3.0-amd64-static.tar.gz


- name: Install the zabbix agent and remove default conf file in /etc/zabbix
  action: shell cd /tmp; tar xvf zabbix_agent-5.0.5-linux-3.0-amd64-static.tar.gz; cd zabbix_agent-5.0.5-linux-3.0-amd64-static ; mkdir /etc/zabbix -p; cp zabbix_agent-5.0.5-linux-3.0-amd64-static/conf/zabbix_agentd.conf /etc/zabbix/ ; cp bin/zabbix_get /usr/bin ; cp bin/zabbix_sender /usr/bin ; cp sbin/zabbix_agentd /usr/sbin ; chmod 755 /usr/bin/zabbix_get ; chmod 755 /usr/bin/zabbix_sender ; chmod 755 /usr/sbin/zabbix_agentd ; cp service/zabbix-agent.service /lib/systemd/system/ ; systemctl start zabbix-agent; systemctl enable zabbix-agent; systemctl daemon-reload;

- name: Start service httpd, if not started
  service:
    name: zabbix-agent
    state: started

# - name: Install zabbix sudoer entries into /etc/sudoers.d
#   template:
#       src: templates/zabbix_sudoers.j2
#       dest: /etc/sudoers.d/zabbix
#       owner: root
#       group: root
#       mode: 0644
  
- name: Install zabbix agent config file into /etc/zabbix
  template:
      src: templates/zabbix_agentd.conf.j2
      dest: /etc/zabbix/zabbix_agentd.conf
      owner: root
      group: root
      mode: 0644
  notify: handler_restart_zabbix_agentd
  
- name: Delete the files in /tmp directory
  action: shell cd /tmp; rm -rf zabbix_agent-5.0.5-linux-3.0-amd64-static*

